version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: case-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: case_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data

  case-service:
    build: ./case-service
    container_name: case-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
